import React,{useEffect,useState}from'react';
import{ArrowDown,ArrowLeft,Camera,CakeSlice,CheckCircle2,Heart,Phone,Sparkles,Utensils,BriefcaseBusiness,MapPin,Users}from'lucide-react';

const scenes={wedding:{ar:'حفلات الزفاف',en:'WEDDINGS',titleAr:'لحظة العمر تبدأ من هنا',titleEn:'The moment starts here',descAr:'تجربة زفاف متكاملة تجمع المكان والضيافة والتجهيز والتنسيق في إيقاع واحد.',descEn:'A complete wedding experience combining venue, hospitality, production and coordination.'},food:{ar:'الضيافة والبوفيه',en:'HOSPITALITY',titleAr:'مائدة تليق بالمناسبة',titleEn:'Hospitality made memorable',descAr:'من استقبال الضيوف إلى آخر طبق، التفاصيل تتحرك حول المناسبة.',descEn:'From guest arrival to the last plate, every detail moves around the occasion.'},official:{ar:'الفعاليات الرسمية',en:'OFFICIAL EVENTS',titleAr:'هيبة المكان في كل تفصيلة',titleEn:'Presence in every detail',descAr:'تشغيل هادئ ومنظم للمؤتمرات والاجتماعات والفعاليات الرسمية.',descEn:'Calm, precise operations for conferences, meetings and official events.'},birthday:{ar:'أعياد الميلاد',en:'BIRTHDAYS',titleAr:'احتفال مليء بالحركة',titleEn:'A celebration in motion',descAr:'تجربة مرنة للضيوف والكيك والضيافة والديكور.',descEn:'A flexible experience for guests, cake, hospitality and styling.'}};
const layouts=['CINEMA','EDITORIAL','VENUE','NIGHT'];
const eventPhotos=[
 ['https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1400&q=85','قاعة احتفال','EVENT HALL'],
 ['https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1400&q=85','زفاف وتنسيق','WEDDING'],
 ['https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1400&q=85','إنتاج وإضاءة','PRODUCTION'],
 ['https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1400&q=85','مناسبة خاصة','CELEBRATION'],
 ['https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1400&q=85','ضيافة وطاولات','HOSPITALITY']
];
const services=[['VENUES','القاعات والأماكن','اختيار وتنسيق المساحة المناسبة حسب عدد الضيوف وطبيعة المناسبة.'],['CELEBRATIONS','الأفراح والخطوبات','تجهيز تجربة كاملة من دخول الضيوف حتى نهاية الاحتفال.'],['HOSPITALITY','الضيافة والبوفيه','تنسيق الطعام والضيافة وخدمة الطاولات بما يناسب شكل الحدث.'],['PRODUCTION','الصوت والإضاءة والتصوير','دعم بصري وسمعي وتصويري يجعل اللحظة قابلة للتذكر.'],['CORPORATE','الفعاليات الرسمية','مؤتمرات واجتماعات واحتفالات شركات بتشغيل دقيق.'],['PRIVATE','أعياد الميلاد والمناسبات الخاصة','مرونة في الديكور والكيك والضيافة والبرنامج.']];
const history=[['2016','البداية','بدأت السرايا برؤية واضحة لتقديم مكان وتجربة منظمة للمناسبات، مع الاهتمام بالتفاصيل التي يلمسها العميل.'],['2018','توسع الخدمات','تطورت التجربة من المكان إلى منظومة خدمات تشمل التجهيز والضيافة والديكور والصوت والإضاءة والتنسيق.'],['2021','خبرة تشغيلية','أصبح التخطيط المسبق وجداول التشغيل ومتابعة التفاصيل جزءًا أساسيًا من طريقة العمل.'],['2024','تنوع أكبر','امتدت الخبرة لتخدم الأفراح والخطوبات وأعياد الميلاد والفعاليات الرسمية والاجتماعات.'],['2026','السرايا اليوم','بعد أكثر من 10 سنوات من العمل والتطور، تجمع السرايا المكان والخدمة والتنسيق والتشغيل في تجربة واحدة.']];

function CustomerHome({lang='ar',onLogin,onInquiry,onToggleLang}){
 const[layout,setLayout]=useState(0),[scene,setScene]=useState('wedding'),[y,setY]=useState(0);
 useEffect(()=>{const f=()=>setY(window.scrollY);addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);
 const ar=lang==='ar',go=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 const s=scenes[scene];
 return <div className={'customer-home layout-'+layout} style={{'--scroll':y+'px',direction:ar?'rtl':'ltr'}}>
  <section className="customer-hero" id="customer-top">
   <div className="hero-atmosphere"><div className="hero-light a"/><div className="hero-light b"/><div className="hero-columns"/><div className={'hero-object '+scene}>{scene==='wedding'?<Heart/>:scene==='food'?<Utensils/>:scene==='official'?<Camera/>:<CakeSlice/>}</div><div className="hero-floor"/></div>
   <header className="customer-nav"><button className="customer-logo" onClick={()=>go('customer-top')}><b>S</b><span><strong>SARAYA</strong><small>EVENT MANAGEMENT · EGYPT</small></span></button><nav>{(ar?[['القاعات','venues'],['الفعاليات','events'],['الخدمات','services'],['عن السرايا','story'],['تواصل','contact']]:[['VENUES','venues'],['EVENTS','events'],['SERVICES','services'],['ABOUT','story'],['CONTACT','contact']]).map(([n,id])=><button key={id} onClick={()=>go(id)}>{n}</button>)}</nav><div className="customer-nav-actions"><button className="language-toggle" onClick={onToggleLang}>{ar?'العربية ↔ EN':'EN ↔ العربية'}</button><button className="staff-link" onClick={onLogin}>Staff Login</button></div></header>
   <div className="hero-copy"><span className="hero-kicker">MIDDLE EAST · EGYPT · SARAYA</span><div className="hero-index"><b>0{layout+1}</b><small>/ 04</small></div><span className="scene-label">{ar?s.ar:s.en}</span><h1>{ar?s.titleAr:s.titleEn}</h1><p>{ar?s.descAr:s.descEn}</p><div className="scene-buttons">{Object.keys(scenes).map(k=><button className={scene===k?'active':''} onClick={()=>setScene(k)} key={k}>{ar?scenes[k].ar:scenes[k].en}</button>)}</div><div className="hero-buttons"><button className="book-hero" onClick={onInquiry}><Phone/>{ar?'ابدأ الحجز':'Start booking'}</button><button className="explore-hero" onClick={()=>go('story')}>{ar?'اكتشف قصتنا':'Explore our story'}<ArrowDown/></button></div></div>
   <div className="layout-switcher"><span>{ar?'التصميم':'LAYOUT'}</span>{layouts.map((x,i)=><button key={x} className={layout===i?'active':''} onClick={()=>setLayout(i)}><b>0{i+1}</b><small>{x}</small></button>)}</div><div className="scroll-cue" onClick={()=>go('venues')}><span>{ar?'مرر لاكتشاف التجربة':'SCROLL TO EXPLORE'}</span><ArrowDown/></div>
  </section>
  <section id="venues" className="customer-section venue-experience"><span className="section-kicker">01 · VENUES</span><div className="section-head"><h2>{ar?'المكان ليس مجرد قاعة':'A venue is more than a room'}</h2><p>{ar?'نصمم استخدام المكان حول حركة الضيوف والطاولات والمسرح والضيافة والإضاءة، بحيث تشعر أن كل تفصيلة لها مكان.':'We shape the space around guest flow, tables, stage, hospitality and lighting so every detail has a purpose.'}</p></div><div className="venue-motion" onClick={()=>setScene('wedding')}><div className="v-back"/><div className="v-mid"/><div className="v-front"><strong>SARAYA</strong><span>{ar?'القاعة الرئيسية':'THE MAIN HALL'}</span></div><button onClick={e=>{e.stopPropagation();setScene('food')}}><Utensils/></button><button onClick={e=>{e.stopPropagation();setScene('official')}}><Camera/></button></div></section>
  <section id="gallery" className="customer-section photo-gallery-section"><span className="section-kicker">02 · VISUAL DIARY</span><div className="section-head"><h2>{ar?'صور تتحرك مع التجربة':'A visual diary in motion'}</h2><p>{ar?'لقطات مختارة من أجواء القاعات والزفاف والإضاءة والضيافة. مرر أو مرر المؤشر فوق الصور لتدخل في طبقات المشهد.':'A rotating selection of venue, wedding, production and hospitality moments. Scroll and hover to move through the visual layers.'}</p></div><div className="photo-mosaic">{eventPhotos.map(([src,title,label],i)=><button key={src} className={'photo-tile p'+i} onClick={onInquiry}><img src={src} alt={title} loading={i>1?'lazy':'eager'}/><span><small>{label}</small><b>{ar?title:label}</b></span></button>)}</div></section>
  <section className="customer-section model-studio-section"><span className="section-kicker">03 · 3D EVENT STUDIO</span><div className="section-head"><h2>{ar?'شاهد المكان كجسم ثلاثي الأبعاد':'Explore the event space in real 3D'}</h2><p>{ar?'نماذج ثلاثية الأبعاد حقيقية للقاعات والأثاث المرتبط بالمناسبات، مع دوران وتكبير باللمس أو الماوس.':'Real 3D event assets for halls and seating, with interactive orbit and zoom on desktop or touch.'}</p></div><div className="model-stage"><div className="model-card large"><div className="model-badge">01 · HALL</div><model-viewer src="https://cdn.3dassets.dev/assets/35232/v1/model.glb" camera-controls auto-rotate rotation-per-second="14deg" shadow-intensity="1.2" exposure="1.05" environment-image="neutral" camera-orbit="25deg 68deg 7m" field-of-view="35deg" alt="3D event hall with stage, tables and chairs"></model-viewer><div className="model-caption"><b>{ar?'قاعة مناسبات كاملة':'Complete event hall'}</b><span>{ar?'مسرح · طاولات · كراسي · تجهيزات':'Stage · tables · chairs · event setup'}</span></div></div><div className="model-stack"><div className="model-card"><div className="model-badge">02 · WEDDING SEATING</div><model-viewer src="https://cdn.3dassets.dev/assets/39391/v1/model.glb" camera-controls auto-rotate rotation-per-second="-18deg" shadow-intensity="1" environment-image="neutral" camera-orbit="-20deg 70deg 2.7m" field-of-view="30deg" alt="3D row of decorated wedding aisle chairs"></model-viewer><div className="model-caption"><b>{ar?'كراسي ممر الزفاف':'Wedding aisle seating'}</b><span>{ar?'تفصيلة قابلة للدوران':'Interactive 3D detail'}</span></div></div><div className="model-specs"><span><b>360°</b>{ar?' دوران':' ORBIT'}</span><span><b>3D</b>{ar?' نماذج حقيقية':' REAL MODELS'}</span><span><b>AR</b>{ar?' جاهز للمستقبل':' READY'}</span></div></div></div></section>
  <section id="events" className="customer-section dark-customer"><span className="section-kicker">04 · EVENTS</span><h2>{ar?'كل مناسبة لها إيقاعها':'Every event has its own rhythm'}</h2><div className="customer-service-grid">{services.map((x,i)=><button key={x[0]} onClick={()=>{setScene(i===0?'wedding':i===2?'food':i===4?'official':'birthday');go('customer-top')}}><b>0{i+1}</b><small>{x[0]}</small><h3>{ar?x[1]:x[0]}</h3><p>{x[2]}</p><ArrowLeft/></button>)}</div></section>
  <section id="services" className="customer-section process-customer"><span className="section-kicker">05 · THE JOURNEY</span><div className="section-head"><h2>{ar?'من أول مكالمة حتى آخر ضيف':'From first call to last guest'}</h2><p>{ar?'رحلة واضحة: نفهم المناسبة، نحدد الخطة، ننسق الخدمات، نجهز، ثم ندير يوم الحدث.':'A clear journey: understand, shape, coordinate, prepare, then deliver the event day.'}</p></div><div className="journey">{(ar?['نسمع الفكرة','نحدد المكان والخطة','ننسق الخدمات','نجهز ونختبر','ندير يوم المناسبة']:['Listen','Shape the plan','Coordinate','Prepare & test','Deliver']).map((x,i)=><button key={x} onClick={onInquiry}><b>0{i+1}</b><span>{x}</span><i/></button>)}</div></section>
  <section id="story" className="customer-section story-customer"><span className="section-kicker">06 · MORE THAN 10 YEARS</span><div className="section-head"><h2>{ar?'أكثر من 10 سنوات من التطور':'More than 10 years of evolution'}</h2><p>{ar?'منذ البداية، تطورت السرايا من التركيز على المكان والتجهيز إلى إدارة تجربة مناسبات متكاملة في مصر، مع خبرة عملية في التشغيل والخدمات والتنسيق.':'Since the beginning, Saraya has evolved from venue and setup into a complete event experience in Egypt, building practical experience in operations, services and coordination.'}</p></div><div className="history-rail">{history.map(([yr,title,text])=><article key={yr}><b>{yr}</b><div><h3>{ar?title:({البداية:'The beginning','توسع الخدمات':'Services expanded','خبرة تشغيلية':'Operational experience','تنوع أكبر':'More event types','السرايا اليوم':'Saraya today'}[title]||title)}</h3><p>{text}</p></div></article>)}</div></section>
  <section id="contact" className="customer-contact"><div><span>MIDDLE EAST · EGYPT</span><h2>{ar?'جاهزون لنبدأ معك':'Ready to start?'}</h2><p>{ar?'أرسل التاريخ المتوقع، عدد الضيوف ونوع المناسبة. فريق السرايا سيحوّل التفاصيل الأولى إلى خطوة واضحة للحجز.':'Send your expected date, guest count and event type. Saraya will turn the first details into a clear booking step.'}</p></div><div><button onClick={onInquiry}><Phone/>{ar?'احجز مناسبتك':'Book your event'}</button><button onClick={()=>go('customer-top')}><ArrowDown/>{ar?'العودة للبداية':'Back to top'}</button></div></section>
  <footer className="customer-footer"><div><b>S</b><strong>SARAYA EVENT</strong></div><span><MapPin/> Egypt · Middle East</span><span><Users/> Weddings · Corporate · Private Events</span><button onClick={onInquiry}><Sparkles/>{ar?'تحدث مع السرايا':'Talk to Saraya'}</button></footer>
 </div>
}
export default CustomerHome;
