import React,{useEffect,useState}from'react';
import{ArrowDown,ArrowLeft,Camera,CakeSlice,CheckCircle2,Heart,Phone,Sparkles,Utensils,BriefcaseBusiness,MapPin,Users}from'lucide-react';

const scenes={wedding:{ar:'حفلات الزفاف',en:'WEDDINGS',titleAr:'لحظة العمر تبدأ من هنا',titleEn:'The moment starts here',descAr:'تجربة زفاف متكاملة تجمع المكان والضيافة والتجهيز والتنسيق في إيقاع واحد.',descEn:'A complete wedding experience combining venue, hospitality, production and coordination.'},food:{ar:'الضيافة والبوفيه',en:'HOSPITALITY',titleAr:'مائدة تليق بالمناسبة',titleEn:'Hospitality made memorable',descAr:'من استقبال الضيوف إلى آخر طبق، التفاصيل تتحرك حول المناسبة.',descEn:'From guest arrival to the last plate, every detail moves around the occasion.'},official:{ar:'الفعاليات الرسمية',en:'OFFICIAL EVENTS',titleAr:'هيبة المكان في كل تفصيلة',titleEn:'Presence in every detail',descAr:'تشغيل هادئ ومنظم للمؤتمرات والاجتماعات والفعاليات الرسمية.',descEn:'Calm, precise operations for conferences, meetings and official events.'},birthday:{ar:'أعياد الميلاد',en:'BIRTHDAYS',titleAr:'احتفال مليء بالحركة',titleEn:'A celebration in motion',descAr:'تجربة مرنة للضيوف والكيك والضيافة والديكور.',descEn:'A flexible experience for guests, cake, hospitality and styling.'}};
const layouts=['CINEMA','EDITORIAL','VENUE','NIGHT'];
const eventPhotoSets=[
 [
  ['https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1400&q=85','قاعة فاخرة','LUXURY HALL'],
  ['https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1400&q=85','تفاصيل الزفاف','WEDDING DETAILS'],
  ['https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1400&q=85','طاولات وضيافة','TABLESCAPE'],
  ['https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1400&q=85','احتفال ليلي','NIGHT EVENT']
 ],
 [
  ['https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1400&q=85','تنسيق مائدة','EDITORIAL TABLE'],
  ['https://images.unsplash.com/photo-1478146896981-b80fe463b330?auto=format&fit=crop&w=1400&q=85','زهور وتفاصيل','FLORAL DESIGN'],
  ['https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1400&q=85','ضيافة راقية','FINE HOSPITALITY'],
  ['https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1400&q=85','مساحة احتفال','EDITORIAL VENUE']
 ],
 [
  ['https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1400&q=85','إنتاج مباشر','LIVE PRODUCTION'],
  ['https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=1400&q=85','إضاءة ومسرح','STAGE LIGHTING'],
  ['https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1400&q=85','جمهور وفعاليات','LIVE AUDIENCE'],
  ['https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1400&q=85','حفلة موسيقية','MUSIC NIGHT']
 ],
 [
  ['https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop&w=1400&q=85','حفلة عيد ميلاد','BIRTHDAY'],
  ['https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1400&q=85','ديكور احتفالي','PARTY DECOR'],
  ['https://images.unsplash.com/photo-1519671282429-b44660ead0a7?auto=format&fit=crop&w=1400&q=85','ألوان ومرح','CELEBRATION'],
  ['https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1400&q=85','تجمع خاص','PRIVATE PARTY']
 ]
];
const modelSets=[
 ['https://cdn.3dassets.dev/assets/35232/v1/model.glb','https://cdn.3dassets.dev/assets/35202/v1/model.glb','LUXURY HALL','TABLE TROLLEY'],
 ['https://cdn.3dassets.dev/assets/39413/v1/model.glb','https://cdn.3dassets.dev/assets/39377/v1/model.glb','WEDDING CHAPEL','CEREMONY DAIS'],
 ['https://cdn.3dassets.dev/assets/33938/v1/model.glb','https://cdn.3dassets.dev/assets/35925/v1/model.glb','LIVE FESTIVAL','THEATRE STAGE'],
 ['https://cdn.3dassets.dev/assets/35925/v1/model.glb','https://cdn.3dassets.dev/assets/39375/v1/model.glb','PARTY THEATRE','CHAPEL STEEPLE']
];
const services=[['VENUES','القاعات والأماكن','اختيار وتنسيق المساحة المناسبة حسب عدد الضيوف وطبيعة المناسبة.'],['CELEBRATIONS','الأفراح والخطوبات','تجهيز تجربة كاملة من دخول الضيوف حتى نهاية الاحتفال.'],['HOSPITALITY','الضيافة والبوفيه','تنسيق الطعام والضيافة وخدمة الطاولات بما يناسب شكل الحدث.'],['PRODUCTION','الصوت والإضاءة والتصوير','دعم بصري وسمعي وتصويري يجعل اللحظة قابلة للتذكر.'],['CORPORATE','الفعاليات الرسمية','مؤتمرات واجتماعات واحتفالات شركات بتشغيل دقيق.'],['PRIVATE','أعياد الميلاد والمناسبات الخاصة','مرونة في الديكور والكيك والضيافة والبرنامج.']];
const history=[['2016','البداية','بدأت السرايا برؤية واضحة لتقديم مكان وتجربة منظمة للمناسبات، مع الاهتمام بالتفاصيل التي يلمسها العميل.'],['2018','توسع الخدمات','تطورت التجربة من المكان إلى منظومة خدمات تشمل التجهيز والضيافة والديكور والصوت والإضاءة والتنسيق.'],['2021','خبرة تشغيلية','أصبح التخطيط المسبق وجداول التشغيل ومتابعة التفاصيل جزءًا أساسيًا من طريقة العمل.'],['2024','تنوع أكبر','امتدت الخبرة لتخدم الأفراح والخطوبات وأعياد الميلاد والفعاليات الرسمية والاجتماعات.'],['2026','السرايا اليوم','بعد أكثر من 10 سنوات من العمل والتطور، تجمع السرايا المكان والخدمة والتنسيق والتشغيل في تجربة واحدة.']];

function CustomerHome({lang='ar',onLogin,onInquiry,onToggleLang}){
 const[layout,setLayout]=useState(0),[scene,setScene]=useState('wedding'),[y,setY]=useState(0),[mono,setMono]=useState('white');
 useEffect(()=>{const f=()=>setY(window.scrollY);addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);
 const ar=lang==='ar',go=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 const s=scenes[scene];
 return <div className={'customer-home layout-'+layout+' mono-'+mono} style={{'--scroll':y+'px',direction:ar?'rtl':'ltr'}}>
  <section className="customer-hero" id="customer-top">
   <div className="hero-atmosphere"><div className="hero-light a"/><div className="hero-light b"/><div className="hero-columns"/><div className={'hero-object '+scene}>{scene==='wedding'?<Heart/>:scene==='food'?<Utensils/>:scene==='official'?<Camera/>:<CakeSlice/>}</div><div className="hero-floor"/></div>
   <header className="customer-nav"><button className="customer-logo" onClick={()=>go('customer-top')}><b>S</b><span><strong>SARAYA</strong><small>EVENT MANAGEMENT · EGYPT</small></span></button><nav>{(ar?[['القاعات','venues'],['الفعاليات','events'],['الخدمات','services'],['عن السرايا','story'],['تواصل','contact']]:[['VENUES','venues'],['EVENTS','events'],['SERVICES','services'],['ABOUT','story'],['CONTACT','contact']]).map(([n,id])=><button key={id} onClick={()=>go(id)}>{n}</button>)}</nav><div className="customer-nav-actions"><button className="language-toggle" onClick={onToggleLang}>{ar?'العربية ↔ EN':'EN ↔ العربية'}</button><button className="mono-toggle" onClick={()=>setMono(mono==='white'?'black':'white')} aria-label="Toggle black and white theme"><i className={mono==='white'?'is-white':''}/><span>{mono==='white'?'BLACK':'WHITE'}</span></button><button className="staff-link" onClick={onLogin}>Staff Login</button></div></header>
   <div className="hero-copy"><span className="hero-kicker">MIDDLE EAST · EGYPT · SARAYA</span><div className="hero-index"><b>0{layout+1}</b><small>/ 04</small></div><span className="scene-label">{ar?s.ar:s.en}</span><h1>{ar?s.titleAr:s.titleEn}</h1><p>{ar?s.descAr:s.descEn}</p><div className="scene-buttons">{Object.keys(scenes).map(k=><button className={scene===k?'active':''} onClick={()=>setScene(k)} key={k}>{ar?scenes[k].ar:scenes[k].en}</button>)}</div><div className="hero-buttons"><button className="book-hero" onClick={onInquiry}><Phone/>{ar?'ابدأ الحجز':'Start booking'}</button><button className="explore-hero" onClick={()=>go('story')}>{ar?'اكتشف قصتنا':'Explore our story'}<ArrowDown/></button></div></div>
   <div className="layout-switcher"><span>{ar?'التصميم':'LAYOUT'}</span>{layouts.map((x,i)=><button key={x} className={layout===i?'active':''} onClick={()=>setLayout(i)}><b>0{i+1}</b><small>{x}</small></button>)}</div><div className="scroll-cue" onClick={()=>go('venues')}><span>{ar?'مرر لاكتشاف التجربة':'SCROLL TO EXPLORE'}</span><ArrowDown/></div>
  </section>
  <section id="venues" className="customer-section venue-experience"><span className="section-kicker">01 · VENUES</span><div className="section-head"><h2>{ar?'المكان ليس مجرد قاعة':'A venue is more than a room'}</h2><p>{ar?'نصمم استخدام المكان حول حركة الضيوف والطاولات والمسرح والضيافة والإضاءة، بحيث تشعر أن كل تفصيلة لها مكان.':'We shape the space around guest flow, tables, stage, hospitality and lighting so every detail has a purpose.'}</p></div><div className="venue-motion" onClick={()=>setScene('wedding')}><div className="v-back"/><div className="v-mid"/><div className="v-front"><strong>SARAYA</strong><span>{ar?'القاعة الرئيسية':'THE MAIN HALL'}</span></div><button onClick={e=>{e.stopPropagation();setScene('food')}}><Utensils/></button><button onClick={e=>{e.stopPropagation();setScene('official')}}><Camera/></button></div></section>
  <section id="gallery" className={'customer-section photo-gallery-section gallery-mode-'+layout}><span className="section-kicker">02 · VISUAL DIARY</span><div className="section-head"><h2>{ar?'صور مختلفة لكل تجربة':'A different visual world for every mode'}</h2><p>{ar?'كل تصميم رئيسي له مجموعة صور خاصة به، وليست مجرد إعادة تلوين للواجهة.':'Each homepage mode has its own photography set — not just a color change.'}</p></div><div className="photo-mosaic">{eventPhotoSets[layout].map(([src,title,label],i)=><button key={src} className={'photo-tile p'+i} onClick={onInquiry}><img src={src} alt={title} loading={i?'lazy':'eager'}/><span><small>{label}</small><b>{ar?title:label}</b></span></button>)}</div></section>
<section className={'customer-section model-studio-section model-mode-'+layout}><span className="section-kicker">03 · 3D EVENT STUDIO</span><div className="section-head"><h2>{ar?'نموذج ثلاثي الأبعاد خاص بهذا التصميم':'A 3D scene selected for this homepage'}</h2><p>{ar?'كل وضع له مشهد 3D وتقديم بصري مختلف.':'Every mode gets its own 3D presentation and interaction treatment.'}</p></div><div className="model-stage"><div className="model-card large"><div className="model-badge">01 · {modelSets[layout][2]}</div><model-viewer src={modelSets[layout][0]} camera-controls auto-rotate rotation-per-second={layout===1?'-10deg':layout===2?'22deg':layout===3?'-25deg':'14deg'} shadow-intensity="1.2" exposure={layout===3?"1.2":"1.05"} environment-image="neutral" camera-orbit={layout===0?"25deg 68deg 7m":layout===1?"-25deg 65deg 6m":layout===2?"45deg 58deg 8m":"0deg 70deg 7m"} field-of-view="35deg" alt="Interactive 3D event model"></model-viewer><div className="model-caption"><b>{ar?['قاعة فاخرة','قاعة تحريرية','مسرح فعاليات','قاعة احتفال'][layout]:modelSets[layout][2]}</b><span>{ar?'مشهد ثلاثي الأبعاد تفاعلي':'Interactive 3D scene'}</span></div></div><div className="model-stack"><div className="model-card"><div className="model-badge">02 · {modelSets[layout][3]}</div><model-viewer src={modelSets[layout][1]} camera-controls auto-rotate rotation-per-second={layout===0?'-18deg':layout===1?'12deg':layout===2?'-24deg':'20deg'} shadow-intensity="1" environment-image="neutral" camera-orbit={layout===3?"30deg 72deg 3m":"-20deg 70deg 2.7m"} field-of-view="30deg" alt="Interactive 3D event detail"></model-viewer><div className="model-caption"><b>{ar?['كراسي الزفاف','تفاصيل الطاولة','تفاصيل الإضاءة','تفاصيل الحفل'][layout]:modelSets[layout][3]}</b><span>{ar?'دوران وتكبير':'Orbit & zoom'}</span></div></div><div className="model-specs"><span><b>360°</b>{ar?' دوران':' ORBIT'}</span><span><b>3D</b>{ar?' مختلف':' PER MODE'}</span><span><b>AR</b>{ar?' جاهز':' READY'}</span></div></div></div></section>
  <section id="events" className="customer-section dark-customer"><span className="section-kicker">04 · EVENTS</span><h2>{ar?'كل مناسبة لها إيقاعها':'Every event has its own rhythm'}</h2><div className="customer-service-grid">{services.map((x,i)=><button key={x[0]} onClick={()=>{setScene(i===0?'wedding':i===2?'food':i===4?'official':'birthday');go('customer-top')}}><b>0{i+1}</b><small>{x[0]}</small><h3>{ar?x[1]:x[0]}</h3><p>{x[2]}</p><ArrowLeft/></button>)}</div></section>
  <section id="services" className="customer-section process-customer"><span className="section-kicker">05 · THE JOURNEY</span><div className="section-head"><h2>{ar?'من أول مكالمة حتى آخر ضيف':'From first call to last guest'}</h2><p>{ar?'رحلة واضحة: نفهم المناسبة، نحدد الخطة، ننسق الخدمات، نجهز، ثم ندير يوم الحدث.':'A clear journey: understand, shape, coordinate, prepare, then deliver the event day.'}</p></div><div className="journey">{(ar?['نسمع الفكرة','نحدد المكان والخطة','ننسق الخدمات','نجهز ونختبر','ندير يوم المناسبة']:['Listen','Shape the plan','Coordinate','Prepare & test','Deliver']).map((x,i)=><button key={x} onClick={onInquiry}><b>0{i+1}</b><span>{x}</span><i/></button>)}</div></section>
  <section id="story" className="customer-section story-customer"><span className="section-kicker">06 · MORE THAN 10 YEARS</span><div className="section-head"><h2>{ar?'أكثر من 10 سنوات من التطور':'More than 10 years of evolution'}</h2><p>{ar?'منذ البداية، تطورت السرايا من التركيز على المكان والتجهيز إلى إدارة تجربة مناسبات متكاملة في مصر، مع خبرة عملية في التشغيل والخدمات والتنسيق.':'Since the beginning, Saraya has evolved from venue and setup into a complete event experience in Egypt, building practical experience in operations, services and coordination.'}</p></div><div className="history-rail">{history.map(([yr,title,text])=><article key={yr}><b>{yr}</b><div><h3>{ar?title:({البداية:'The beginning','توسع الخدمات':'Services expanded','خبرة تشغيلية':'Operational experience','تنوع أكبر':'More event types','السرايا اليوم':'Saraya today'}[title]||title)}</h3><p>{text}</p></div></article>)}</div></section>
  <section id="contact" className="customer-contact"><div><span>MIDDLE EAST · EGYPT</span><h2>{ar?'جاهزون لنبدأ معك':'Ready to start?'}</h2><p>{ar?'أرسل التاريخ المتوقع، عدد الضيوف ونوع المناسبة. فريق السرايا سيحوّل التفاصيل الأولى إلى خطوة واضحة للحجز.':'Send your expected date, guest count and event type. Saraya will turn the first details into a clear booking step.'}</p></div><div><button onClick={onInquiry}><Phone/>{ar?'احجز مناسبتك':'Book your event'}</button><button onClick={()=>go('customer-top')}><ArrowDown/>{ar?'العودة للبداية':'Back to top'}</button></div></section>
  <footer className="customer-footer"><div><b>S</b><strong>SARAYA EVENT</strong></div><span><MapPin/> Egypt · Middle East</span><span><Users/> Weddings · Corporate · Private Events</span><button onClick={onInquiry}><Sparkles/>{ar?'تحدث مع السرايا':'Talk to Saraya'}</button></footer>
 </div>
}
export default CustomerHome;
