import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{CalendarDays,Users,WalletCards,Receipt,Plus,Search,LayoutDashboard,Settings,Bell,Clock3,CheckCircle2,X,MoreHorizontal,Banknote,Building2,ChevronLeft,ChevronRight,Trash2,Edit3,FileText,TrendingUp,MinusCircle,Menu,Download,Eye,Heart,Utensils,CakeSlice,BriefcaseBusiness,Camera,LogIn,ArrowLeft,UserRound,ShieldCheck}from'lucide-react';
import'./styles.css';
import CustomerHome from './customerHome';
import InquiryModal from './inquiryModal';

const initialBookings=[
{id:1,client:'أحمد محمد',phone:'01000000000',type:'فرح',date:'2026-10-10',start:'19:00',end:'01:00',venue:'القاعة الرئيسية',status:'مؤكد',total:85000,paid:30000,services:['دي جي','تصوير']},
{id:2,client:'سارة علي',phone:'01111111111',type:'خطوبة',date:'2026-10-12',start:'18:00',end:'23:00',venue:'قاعة اللوتس',status:'مبدئي',total:42000,paid:10000,services:['ديكور']},
{id:3,client:'محمد حسن',phone:'01222222222',type:'عيد ميلاد',date:'2026-10-18',start:'20:00',end:'00:00',venue:'الحديقة',status:'مؤكد',total:28000,paid:28000,services:['بوفيه']}
];
const initialExpenses=[
{id:1,title:'كهرباء ومرافق',category:'تشغيل',date:'2026-10-02',amount:6500},
{id:2,title:'صيانة القاعة',category:'صيانة',date:'2026-10-04',amount:3500},
{id:3,title:'مستلزمات ضيافة',category:'مشتريات',date:'2026-10-06',amount:4200}
];
const initialServices=[
{id:1,name:'دي جي',price:5000,unit:'للحفل'},
{id:2,name:'تصوير',price:7500,unit:'للحفل'},
{id:3,name:'ديكور',price:9000,unit:'للحفل'},
{id:4,name:'بوفيه',price:12000,unit:'للحفل'}
];
const halls=['القاعة الرئيسية','قاعة اللوتس','الحديقة','المسرح'];
const types=['فرح','خطوبة','عيد ميلاد','مؤتمر','حفلة'];
const money=n=>new Intl.NumberFormat('ar-EG').format(Number(n)||0)+' ج.م';
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
const saveStore=(k,v)=>localStorage.setItem(k,JSON.stringify(v));

function BookingModal({close,save,edit}){const[f,setF]=useState(edit||{client:'',phone:'',type:'فرح',date:'',start:'',end:'',venue:halls[0],status:'مبدئي',total:'',paid:'',services:[]});const s=(k,v)=>setF(x=>({...x,[k]:v}));const toggle=x=>s('services',f.services.includes(x)?f.services.filter(y=>y!==x):[...f.services,x]);return <div className="overlay"><div className="modal wide"><div className="modal-head"><div><h2>{edit?'تعديل الحجز':'حجز جديد'}</h2><p>بيانات العميل والمناسبة والحساب</p></div><button className="icon" onClick={close}><X/></button></div><div className="form">{[['client','اسم العميل','text'],['phone','رقم الهاتف','tel'],['date','تاريخ المناسبة','date'],['start','وقت البداية','time'],['end','وقت النهاية','time'],['total','إجمالي قيمة الحجز','number'],['paid','المدفوع مقدمًا','number']].map(([k,l,t])=><label key={k}>{l}<input type={t} value={f[k]} onChange={e=>s(k,e.target.value)}/></label>)}<label>نوع المناسبة<select value={f.type} onChange={e=>s('type',e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label>القاعة / المكان<select value={f.venue} onChange={e=>s('venue',e.target.value)}>{halls.map(x=><option key={x}>{x}</option>)}</select></label><label>الحالة<select value={f.status} onChange={e=>s('status',e.target.value)}><option>مبدئي</option><option>مؤكد</option><option>ملغي</option></select></label><div className="field"><span>الخدمات</span><div className="chips">{initialServices.map(x=><button type="button" className={f.services.includes(x.name)?'chip selected':'chip'} onClick={()=>toggle(x.name)} key={x.id}>{x.name}</button>)}</div></div></div><div className="actions"><button className="btn ghost" onClick={close}>إلغاء</button><button className="btn primary" onClick={()=>save({...f,total:+f.total||0,paid:+f.paid||0})}><CheckCircle2/>{edit?'حفظ التعديل':'حفظ الحجز'}</button></div></div></div>}

const sceneData={wedding:{label:'حفلات الزفاف',title:'لحظة العمر تبدأ من هنا',desc:'أجواء زفاف راقية، تفاصيل منظمة، وفريق جاهز لكل لحظة.',icon:Heart},food:{label:'الضيافة والبوفيه',title:'مائدة تليق بالمناسبة',desc:'تنسيق الضيافة والخدمة حول القاعة من لحظة التجهيز حتى نهاية الحفل.',icon:Utensils},official:{label:'الفعاليات الرسمية',title:'هيبة المكان في كل تفصيلة',desc:'تنظيم المؤتمرات والاجتماعات والفعاليات الرسمية باحترافية هادئة.',icon:BriefcaseBusiness},birthday:{label:'أعياد الميلاد',title:'احتفال مليء بالحركة',desc:'تصميم تجربة مرنة للضيوف، الطعام، الكيك، والتجهيزات.',icon:CakeSlice}};
const homeLayouts=[
 {id:1,name:'CINEMA',tag:'المشهد السينمائي',title:'كل لحظة تبدأ بمشهد',desc:'ادخل إلى أجواء السرايا قبل أن تبدأ المناسبة.',className:'layout-cinema'},
 {id:2,name:'EDITORIAL',tag:'التصميم التحريري',title:'تفاصيل تُرى قبل أن تُحكى',desc:'تجربة فاخرة تجمع الصورة، الحركة، والخدمات في تكوين واحد.',className:'layout-editorial'},
 {id:3,name:'VENUE',tag:'جولة القاعة',title:'المكان هو بطل الحكاية',desc:'تحرك بصري داخل القاعة مع طبقات إضاءة وعمق ومساحة.',className:'layout-venue'},
 {id:4,name:'NIGHT',tag:'ليلة السرايا',title:'ليلة لا تشبه غيرها',desc:'واجهة داكنة هادئة بإيقاع ضوئي متحرك للمناسبات الراقية.',className:'layout-night'}
];
function SceneVisual({scene,layout}){return <div className={'visual-stage '+homeLayouts[layout-1].className}>
 <div className="visual-glow glow-a"/><div className="visual-glow glow-b"/><div className="venue-architecture"><i/><i/><i/><i/><i/></div>
 {scene==='wedding'&&<div className="dress"><div className="dress-top"/><div className="dress-skirt"/></div>}
 {scene==='food'&&<div className="food-table">{['🍽️','🥗','🍖','🍰','🥂','🍇','🍗'].map((x,i)=><span key={i} style={{'--i':i}}>{x}</span>)}</div>}
 {scene==='official'&&<><div className="camera"><Camera/></div><div className="camera-sweep"/></>}
 {scene==='birthday'&&<div className="birthday-scene"><CakeSlice/><div>🎈 🎈 🎈</div></div>}
 <div className="floating-orb orb-a"/><div className="floating-orb orb-b"/>
 </div>}
function LayoutCells({layout,setLayout}){return <div className="layout-cells" aria-label="اختيار تصميم الصفحة الرئيسية">{homeLayouts.map(x=><button key={x.id} className={layout===x.id?'active':''} onClick={()=>setLayout(x.id)}><b>{x.id}</b><span>{x.name}</span></button>)}</div>}
function Home({login,lang,onToggleLang}){const[scene,setScene]=useState('wedding');const[layout,setLayout]=useState(1);const S=sceneData[scene].icon;const current=homeLayouts[layout-1];return <div className="landing">
 <div className={'home-layout '+current.className}>
  <SceneVisual scene={scene} layout={layout}/><div className="scene-vignette"/>
  <div className="landing-nav"><div className="landing-brand"><b>S</b><div><strong>SARAYA</strong><small>EVENT MANAGEMENT</small></div></div><div className="nav-center">{(lang==='ar'?['القاعات','الفعاليات','الخدمات','المعرض']:['VENUES','EVENTS','SERVICES','GALLERY']).map(x=><span key={x}>{x}</span>)}</div><div className="home-tools"><button type="button" className="language-toggle" onClick={onToggleLang}>{lang==='ar'?'العربية ↔ EN':'EN ↔ العربية'}</button><button className="login-btn" onClick={login}><LogIn/>تسجيل الدخول</button></div></div>
  <div className="layout-counter"><span>LAYOUT</span><strong>0{layout}</strong><small>/ 04</small></div>
  <div className="landing-content"><div className="eyebrow"><S/> {sceneData[scene].label} <i/> {current.tag}</div><h1>{current.title}</h1><p>{current.desc}</p>
   <div className="scene-switch">{Object.entries(sceneData).map(([k,v])=><button className={scene===k?'selected':''} onClick={()=>setScene(k)} key={k}>{v.label}</button>)}</div>
   <div className="hero-actions"><button className="hero-login" onClick={login}>{lang==='ar'?'اكتشف السرايا':'Discover Saraya'} <ArrowLeft/></button><span>{lang==='ar'?'تجربة تجريبية · الحركة أولاً':'Demo Experience · Motion First'}</span></div>
  </div>
  <div className="layout-swipe"><span>{lang==='ar'?'اسحب للتصاميم':'SWIPE LAYOUTS'}</span><LayoutCells layout={layout} setLayout={setLayout}/></div>
  <div className="camera-status"><span className="rec"/><Camera/> {lang==='ar'?'تجربة حركية':'MOTION EXPERIENCE'} <b>4K</b></div>
 </div>
 <OrgMatrix/>
 </div>}
function OrgMatrix(){return <section className="org-section"><div className="org-intro"><span>STRUCTURE</span><h2>مصفوفة فريق السرايا</h2><p>فريق إداري أساسي صغير يقود التشغيل، مدعوم بشبكة كبيرة من المساعدين والعمالة الميدانية حسب حجم كل فعالية.</p></div><div className="org-matrix"><div className="org-core"><div className="org-label">الفريق الأساسي</div>{[['مدير القاعة','الإدارة والتشغيل'],['مدير العمليات','التخطيط والمتابعة'],['مسؤول الحجوزات','العملاء والعقود'],['المحاسبة','الدفعات والمصروفات']].map(x=><div className="org-card" key={x[0]}><ShieldCheck/><div><b>{x[0]}</b><small>{x[1]}</small></div></div>)}</div><div className="org-connector">↓</div><div className="org-ground"><div className="org-label">فريق التشغيل الميداني <strong>مرن حسب المناسبة</strong></div><div className="helper-cloud">{['ضيافة','خدمة طاولات','تجهيز','نظافة','أمن','صوت وإضاءة','ديكور','تصوير','استقبال','مساعدون'].map((x,i)=><span key={i}>{x}</span>)}</div><p><Users/> عدد كبير من المساعدين الميدانيين يتم توزيعهم حسب عدد الضيوف ونوع الفعالية، وليس كموظفين إداريين دائمين.</p></div></div></section>}
function Login({close,enter}){const[name,setName]=useState('');return <div className="overlay login-overlay"><div className="login-card"><button className="icon" onClick={close}><X/></button><div className="login-logo">S</div><span>SARAYA EVENT</span><h2>تسجيل الدخول</h2><p>ادخل إلى لوحة إدارة الفعاليات التجريبية</p><label>اسم المستخدم<input value={name} onChange={e=>setName(e.target.value)} placeholder="مثال: المدير"/></label><label>كلمة المرور<input type="password" placeholder="••••••••"/></label><button className="btn primary login-submit" onClick={()=>enter(name||'مدير السرايا')}><LogIn/>دخول للنظام</button><small>Demo Mode · لا يتم إرسال أي بيانات</small></div></div>}
function App(){const[lang,setLang]=useState(()=>load('saraya_lang','ar'));const toggleLang=()=>setLang(x=>{const n=x==='ar'?'en':'ar';saveStore('saraya_lang',n);return n});const[home,setHome]=useState(true),[login,setLogin]=useState(false),[user,setUser]=useState('مدير السرايا'),[a,setA]=useState('dashboard'),[bs,setBs]=useState(()=>load('saraya_bookings',initialBookings)),[expenses,setExpenses]=useState(()=>load('saraya_expenses',initialExpenses)),[services,setServices]=useState(()=>load('saraya_services',initialServices)),[q,setQ]=useState(''),[modal,setModal]=useState(null),[detail,setDetail]=useState(null),[toast,setToast]=useState('');
const nav=[['dashboard','لوحة التحكم',LayoutDashboard],['bookings','الحجوزات',CalendarDays],['calendar','التقويم',CalendarDays],['clients','العملاء',Users],['payments','الدفعات',WalletCards],['expenses','المصروفات',Receipt],['services','الخدمات',Building2],['reports','التقارير',TrendingUp]];
const setBookings=v=>{setBs(v);saveStore('saraya_bookings',v)};const setEx=v=>{setExpenses(v);saveStore('saraya_expenses',v)};
const paid=bs.reduce((s,b)=>s+b.paid,0),revenue=bs.reduce((s,b)=>s+b.total,0),due=revenue-paid,exp=expenses.reduce((s,e)=>s+e.amount,0),profit=paid-exp;
const clients=useMemo(()=>{const m={};bs.forEach(b=>m[b.phone]={name:b.client,phone:b.phone,bookings:(m[b.phone]?.bookings||0)+1,total:(m[b.phone]?.total||0)+b.total,paid:(m[b.phone]?.paid||0)+b.paid});return Object.values(m)},[bs]);
const filtered=useMemo(()=>bs.filter(b=>[b.client,b.phone,b.type,b.venue,b.status].join(' ').includes(q)),[bs,q]);
const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2500)};
const addBooking=f=>{setBookings([...bs,{...f,id:Date.now()}]);setModal(null);notify('تم حفظ الحجز بنجاح')};
const editBooking=f=>{setBookings(bs.map(b=>b.id===f.id?f:b));setModal(null);notify('تم تحديث الحجز')};
const deleteBooking=id=>{setBookings(bs.filter(b=>b.id!==id));setDetail(null);notify('تم حذف الحجز')};

if(home)return <><CustomerHome lang={lang} onToggleLang={toggleLang} onLogin={()=>setLogin(true)} onInquiry={()=>setBookingRequestOpen(true)}/>{bookingRequestOpen&&<InquiryModal close={()=>setBookingRequestOpen(false)} lang={lang}/>} {login&&<Login close={()=>setLogin(false)} enter={n=>{setUser(n);setLogin(false);setHome(false)}}/>}</>;
return <div className={'shell '+lang}><aside><div className="brand"><b>S</b><div><strong>SARAYA</strong><small>EVENT MANAGEMENT</small></div></div>{nav.map(([k,l,I])=><button className={a===k?'active':''} onClick={()=>setA(k)} key={k}><I/>{l}</button>)}<button className={a==='settings'?'active':''} onClick={()=>setA('settings')}><Settings/>الإعدادات</button></aside><main><header><div><small>{lang==='ar'?'إدارة القاعة والمناسبات':'Venue & Event Management'}</small><h1>{nav.find(x=>x[0]===a)?.[1]||'الإعدادات'}</h1></div><div className="header-tools"><button type="button" className="language-toggle dashboard-language" onClick={toggleLang}>{lang==='ar'?'العربية ↔ EN':'EN ↔ العربية'}</button><div className="user"><Bell/><span>{user[0]||'S'}</span></div></div></header>
{a==='dashboard'&&<Dashboard bs={bs} paid={paid} due={due} revenue={revenue} exp={exp} profit={profit} setA={setA} openNew={()=>setModal('new')} openDetail={setDetail}/>}
{a==='bookings'&&<Bookings filtered={filtered} q={q} setQ={setQ} openNew={()=>setModal('new')} openDetail={setDetail} edit={b=>setModal(b)} deleteBooking={deleteBooking}/>}
{a==='calendar'&&<Calendar bs={bs} openDetail={setDetail}/>}
{a==='clients'&&<Clients clients={clients} openDetail={setDetail}/>}
{a==='payments'&&<Payments bs={bs} setBookings={setBookings} notify={notify}/>}
{a==='expenses'&&<Expenses expenses={expenses} setEx={setEx} notify={notify}/>}
{a==='services'&&<Services services={services} setServices={v=>{setServices(v);saveStore('saraya_services',v)}}/>}
{a==='reports'&&<Reports bs={bs} expenses={expenses} revenue={revenue} paid={paid} due={due} exp={exp} profit={profit}/>}
{a==='settings'&&<SettingsPage/>}</main>
{modal&&<BookingModal close={()=>setModal(null)} edit={modal==='new'?null:modal} save={modal==='new'?addBooking:editBooking}/>}
{detail&&<BookingDetail b={detail} close={()=>setDetail(null)} edit={()=>{setModal(detail);setDetail(null)}} deleteBooking={deleteBooking}/>}
{toast&&<div className="toast"><CheckCircle2/>{toast}</div>}</div>}

function Dashboard({bs,paid,due,revenue,exp,profit,setA,openNew,openDetail}){return <section><div className="hero"><div><em>SARAYA EVENT</em><h2>كل إدارة القاعة في مكان واحد</h2><p>الحجوزات والعملاء والدفعات والمصروفات والخدمات — كنظام تجريبي متكامل.</p></div><button className="btn primary" onClick={openNew}><Plus/>حجز جديد</button></div><div className="stats"><Stat I={CalendarDays} l="الحجوزات" v={bs.length} n="إجمالي الحجوزات"/><Stat I={Banknote} l="إجمالي المبيعات" v={money(revenue)} n="قيمة الحجوزات"/><Stat I={WalletCards} l="تم التحصيل" v={money(paid)} n="الدفعات المسجلة"/><Stat I={Clock3} l="المتبقي" v={money(due)} n="مستحق التحصيل"/></div><div className="dashboard-grid"><div className="panel"><div className="panel-title"><div><h3>الحجوزات القادمة</h3><p>أقرب المناسبات المجدولة</p></div><button onClick={()=>setA('bookings')}>عرض الكل</button></div>{bs.slice().sort((x,y)=>x.date.localeCompare(y.date)).slice(0,5).map(b=><Row b={b} key={b.id} onClick={()=>openDetail(b)}/>)}</div><div className="panel finance"><div className="panel-title"><div><h3>ملخص مالي</h3><p>الحالة الحالية للنظام التجريبي</p></div></div><div className="finance-row"><span>التحصيل</span><b>{money(paid)}</b></div><div className="finance-row"><span>المصروفات</span><b>{money(exp)}</b></div><div className="finance-row total"><span>صافي النقدية</span><b>{money(profit)}</b></div><div className="mini-note">المتبقي من الحجوزات: <strong>{money(due)}</strong></div></div></div></section>}

function Bookings({filtered,q,setQ,openNew,openDetail,edit,deleteBooking}){return <section><div className="page-title"><div><h2>الحجوزات</h2><p>إدارة جميع المناسبات والحجوزات.</p></div><button className="btn primary" onClick={openNew}><Plus/>حجز جديد</button></div><div className="panel"><div className="toolbar"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="بحث بالعميل، الهاتف، المناسبة أو الحالة"/></div><span className="count">{filtered.length} حجز</span></div><div className="table"><table><thead><tr><th>العميل</th><th>المناسبة</th><th>التاريخ</th><th>الوقت</th><th>المكان</th><th>الإجمالي</th><th>المتبقي</th><th>الحالة</th><th/></tr></thead><tbody>{filtered.map(b=><tr key={b.id} onDoubleClick={()=>openDetail(b)}><td><b>{b.client}</b><small>{b.phone}</small></td><td>{b.type}</td><td>{b.date}</td><td>{b.start} — {b.end}</td><td>{b.venue}</td><td>{money(b.total)}</td><td>{money(b.total-b.paid)}</td><td><span className={'status '+(b.status==='مؤكد'?'ok':b.status==='ملغي'?'cancel':'pending')}>{b.status}</span></td><td><button className="icon" onClick={()=>openDetail(b)}><MoreHorizontal/></button></td></tr>)}</tbody></table></div></div></section>}

function Calendar({bs,openDetail}){const dates=[...new Set(bs.map(b=>b.date))].sort();return <section><div className="page-title"><div><h2>تقويم المناسبات</h2><p>عرض سريع للحجوزات حسب التاريخ.</p></div></div><div className="calendar-grid">{dates.map(d=><div className="day-card" key={d}><div className="day-head"><b>{new Date(d+'T00:00').toLocaleDateString('ar-EG',{weekday:'long'})}</b><span>{d}</span></div>{bs.filter(b=>b.date===d).map(b=><button className="event-card" key={b.id} onClick={()=>openDetail(b)}><strong>{b.client}</strong><span>{b.type} · {b.start}</span><small>{b.venue}</small></button>)}</div>)}{!dates.length&&<Empty text="لا توجد حجوزات"/>}</div></section>}

function Clients({clients,openDetail}){return <section><div className="page-title"><div><h2>العملاء</h2><p>ملف مختصر لكل عميل وحجوزاته.</p></div></div><div className="cards-grid">{clients.map(c=><div className="client-card" key={c.phone}><div className="avatar">{c.name[0]}</div><div><h3>{c.name}</h3><p>{c.phone}</p></div><div className="client-stats"><span><b>{c.bookings}</b> حجوزات</span><span><b>{money(c.total)}</b> إجمالي</span><span><b>{money(c.total-c.paid)}</b> متبقي</span></div><button className="link-btn" onClick={()=>openDetail(null)}>عرض الملف</button></div>)}</div></section>}

function Payments({bs,setBookings,notify}){const addPayment=b=>{const amount=prompt('أدخل قيمة الدفعة',Math.max(0,b.total-b.paid));if(amount===null)return;const n=Number(amount);if(!n||n<0)return;setBookings(bs.map(x=>x.id===b.id?{...x,paid:Math.min(x.total,x.paid+n),status:x.paid+n>=x.total?'مؤكد':x.status}:x));notify('تم تسجيل الدفعة')};return <section><div className="page-title"><div><h2>الدفعات</h2><p>متابعة التحصيل والمبالغ المستحقة.</p></div></div><div className="panel"><div className="table"><table><thead><tr><th>العميل</th><th>الحجز</th><th>الإجمالي</th><th>المدفوع</th><th>المتبقي</th><th>الإجراء</th></tr></thead><tbody>{bs.map(b=><tr key={b.id}><td><b>{b.client}</b></td><td>{b.date} · {b.type}</td><td>{money(b.total)}</td><td className="positive">{money(b.paid)}</td><td className="negative">{money(b.total-b.paid)}</td><td><button className="small-btn" disabled={b.paid>=b.total} onClick={()=>addPayment(b)}>{b.paid>=b.total?'مكتمل':'إضافة دفعة'}</button></td></tr>)}</tbody></table></div></div></section>}

function Expenses({expenses,setEx,notify}){const add=()=>{const title=prompt('اسم المصروف');if(!title)return;const amount=Number(prompt('قيمة المصروف','0'));if(!amount)return;setEx([...expenses,{id:Date.now(),title,category:'عام',date:new Date().toISOString().slice(0,10),amount}]);notify('تم إضافة المصروف')};return <section><div className="page-title"><div><h2>المصروفات</h2><p>تسجيل ومتابعة مصروفات تشغيل القاعة.</p></div><button className="btn primary" onClick={add}><Plus/>مصروف جديد</button></div><div className="panel"><div className="table"><table><thead><tr><th>البيان</th><th>التصنيف</th><th>التاريخ</th><th>القيمة</th><th/></tr></thead><tbody>{expenses.map(e=><tr key={e.id}><td><b>{e.title}</b></td><td>{e.category}</td><td>{e.date}</td><td>{money(e.amount)}</td><td><button className="icon" onClick={()=>setEx(expenses.filter(x=>x.id!==e.id))}><Trash2/></button></td></tr>)}</tbody></table></div></div></section>}

function Services({services,setServices}){const add=()=>{const name=prompt('اسم الخدمة');if(!name)return;const price=Number(prompt('السعر','0'))||0;setServices([...services,{id:Date.now(),name,price,unit:'للحفل'}])};return <section><div className="page-title"><div><h2>الخدمات</h2><p>أسعار الخدمات الإضافية التي يمكن ربطها بالحجز.</p></div><button className="btn primary" onClick={add}><Plus/>خدمة جديدة</button></div><div className="cards-grid">{services.map(s=><div className="service-card" key={s.id}><div className="service-icon"><Building2/></div><h3>{s.name}</h3><p>{s.unit}</p><strong>{money(s.price)}</strong><button className="icon delete-service" onClick={()=>setServices(services.filter(x=>x.id!==s.id))}><Trash2/></button></div>)}</div></section>}

function Reports({bs,expenses,revenue,paid,due,exp,profit}){return <section><div className="page-title"><div><h2>التقارير المالية</h2><p>ملخص الإيرادات والتحصيل والمصروفات والربحية.</p></div><button className="btn ghost" onClick={()=>window.print()}><Download/>طباعة / حفظ PDF</button></div><div className="stats"><Stat I={TrendingUp} l="الإيرادات" v={money(revenue)} n="قيمة الحجوزات"/><Stat I={Banknote} l="التحصيل" v={money(paid)} n="تم تحصيله"/><Stat I={Clock3} l="المستحق" v={money(due)} n="لم يتم تحصيله"/><Stat I={MinusCircle} l="المصروفات" v={money(exp)} n="إجمالي المصروفات"/></div><div className="dashboard-grid"><div className="panel report-box"><h3>صافي النتيجة</h3><div className="big-number">{money(profit)}</div><p>التحصيل الفعلي ناقص المصروفات المسجلة.</p></div><div className="panel report-box"><h3>توزيع الحجوزات</h3>{types.map(t=>{const n=bs.filter(b=>b.type===t).length;return <div className="bar-row" key={t}><span>{t}</span><div><i style={{width:(n/Math.max(bs.length,1))*100+'%'}}/></div><b>{n}</b></div>})}</div></div></section>}

function BookingDetail({b,close,edit,deleteBooking}){if(!b)return null;return <div className="overlay"><div className="modal detail"><div className="modal-head"><div><small>تفاصيل الحجز #{b.id}</small><h2>{b.client}</h2><p>{b.type} · {b.date}</p></div><button className="icon" onClick={close}><X/></button></div><div className="detail-grid"><Info l="الهاتف" v={b.phone}/><Info l="المكان" v={b.venue}/><Info l="الوقت" v={b.start+' — '+b.end}/><Info l="الحالة" v={b.status}/><Info l="الإجمالي" v={money(b.total)}/><Info l="المدفوع" v={money(b.paid)}/><Info l="المتبقي" v={money(b.total-b.paid)}/><Info l="الخدمات" v={b.services?.join('، ')||'لا توجد'}/></div><div className="actions"><button className="btn ghost" onClick={close}>إغلاق</button><button className="btn ghost" onClick={edit}><Edit3/>تعديل</button><button className="btn danger" onClick={()=>deleteBooking(b.id)}><Trash2/>حذف</button></div></div></div>}

function Info({l,v}){return <div className="info"><small>{l}</small><b>{v}</b></div>}function Stat({I,l,v,n}){return <div className="stat"><div><I/></div><small>{l}</small><strong>{v}</strong><span>{n}</span></div>}function Row({b,onClick}){return <button className="row" onClick={onClick}><div className="date"><b>{new Date(b.date+'T00:00').getDate()}</b><small>{new Date(b.date+'T00:00').toLocaleDateString('ar-EG',{month:'short'})}</small></div><div><b>{b.client}</b><span>{b.type} · {b.venue}</span></div><time><Clock3/>{b.start}</time><span className={'status '+(b.status==='مؤكد'?'ok':'pending')}>{b.status}</span></button>}function Empty({text}){return <div className="empty">{text}</div>}function SettingsPage(){return <section><div className="placeholder"><div className="placeholder-icon"><Settings/></div><h2>الإعدادات</h2><p>هذه نسخة Demo حاليًا. البيانات تحفظ محليًا على نفس المتصفح.</p></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
